### ISSUE TITLE
inform user about missing files

### ISSUE THREAD

**Issue by stohrendorf** [stohrendorf/EdisonEngine#115]
check that necessary files exist, otherwise inform the user and show instructions how to fix this

* [ ] audio files (+ download link)
* [ ] level files
* [ ] fmvs
* [ ] add `docs/setup.html` with instructions and proper styling
* [ ] open that document using as portable as possible mechanisms (at least windows/linux support)
* [ ] include documentation files in release targets (see e.g. python dependencies, create new target if necessary)

**Comment by Richard-L** [comment]
Would be nice if this could be handled through an external launcher/wizard for EE. Instead of a download link, consider allowing people to point to:
- TR1 demo (likely one exists and allows people to download assets (more or less) legally)
- original TR1 CDs (main and expansion)
- steam files
- android release (?) Think OpenLara uses that for audio
