### ISSUE TITLE
Unexpected overlays on fullscreen boot

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#161]
![IMG_20210226_102011.jpg](https://user-images.githubusercontent.com/4934209/109281179-43645b80-781c-11eb-8069-2234d7fc6ba5.jpg)

Extremely nitpicky thing, bear with me: With the fullscreen option enabled, EE starts with a black background, a white window in the middle, and the EE loading screen image sitting in the top left. Soon after, it assumes a correct fullscreen look once the main menu appears.

It'd make EE look nicer if the loading screen was assumed fullsize correctly. Could also consider mimicking TR1's loading bar at the bottom, instead of the % count. For my taste personally, I'd also avoid the inclusion of foreign font files as they quickly defer from the original game aesthetic. I'd try to use the game's own typeface as much as possible.

**Comment by stohrendorf** [comment]
The problem with this is that render settings are (currently) not yet available before booting, thus it intializes the window with the default settings and then applies the render settings as loaded from the config file.

About fonts, that's even harder to accomplish, because the in-game font will only be available once the engine booted and loaded at least one level file. Additionally, if you use texture packs, loading that texture pack requires some time, and then the level textures need to be re-built with the hd textures, which also takes some time.

I was looking for a font that looks like the classic TR font, but wasn't lucky to find one, this one is the only one I considered okay-ish _and_ is free.
