### ISSUE TITLE
Missing textures in Tomb of Qualopec

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/EdisonEngine#192]
Engine Version: Beta 7.1

As you can see in the video below, only two sides of the Scion pedestal in Tomb of Qualopec are textured:
https://youtu.be/9KLdodMTnHI

I've tried this with the original data files (from the Premier Collection) and the Braid Fix mod. Both versions show the same issue. Maybe related to #187.

In the original, all four sides are textured:
https://youtu.be/vr104HV7wg0?t=345

**Comment by stohrendorf** [comment]
That's because all meshes are dynamically lit in EE, and there are just not enough static light sources in that room. Additionally, if I remember correctly, and as you can see from the shadowed sides of Lara, the ambient brightness of that room is 0, effectively rendering everything black that's not lit by light sources.
